export const TOAST_TEXT = {
  studentAdded: "Student added successfully!",
  errorAddingStudent: "There was an error adding the student",
  familyAdded: "Family added successfully!",
  errorAddingFamily: "There was an error adding the family",
  teacherAdded: "Teacher added successfully!",
  errorAddingTeacher: "There was an error adding the teacher",
  classAdded: "Class added successfully!",
  errorAddingClass: "There was an error adding the class",
  studentDeleted: "Student deleted successfully!",
  errorStudentDelete: "There was an error deleting the student",
  errorUpdatingStudent: "There was an error updating the student",
  studentUpdated: "Student updated successfully!",
  errorDeletingClass: "There was an error deleting the class",
  classDeleted: "Class deleted successfully!",
  errorUpdatingClass: "There was an error updating the class",
  classUpdated: "Class updated successfully!",
  teacherDeleted: "Teacher deleted successfully!",
  errorDeletingTeacher: "There was an error deleting the teacher",
  teacherUpdated: "Teacher info updated successfully!",
  errorUpdatingTeacher: "There was an error updating teacher info",
  familyUpdated: "Family updated successfully!",
  errorUpdatingFamily: "There was an error updating the family",
  errorAddingStudentToClass: "There was an error adding student(s) to class",
  studentAddedToClass: "Student(s) added to class successfully!",
  errorFetchingAssignedStudents:
    "There was an error getting assigned students for this class",
};
